FROM tensorflow/tensorflow:latest-py3

COPY requirements-unversioned.txt /opt/ml/code/requirements-unversioned.txt
RUN pip install -r /opt/ml/code/requirements-unversioned.txt
# Copies the training code inside the container
COPY . /opt/ml/code/

# Defines train.py as script entrypoint
ENV SAGEMAKER_PROGRAM train_genetic_algorithm.py

ENTRYPOINT ["python", "/opt/ml/code/train_genetic_algorithm.py"]
